# Generated by Django 4.0.5 on 2022-06-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la ciudad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad total de Producto(Bodega)')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto a vender')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Cliente(Consumidor)')),
                ('nombreCli', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('celular', models.IntegerField(max_length=9, verbose_name='Número de celular Cliente')),
                ('direccion', models.CharField(max_length=100, verbose_name='Número de casa y dirección pasajes,etc.')),
                ('cod_ciud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioPet.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la boleta')),
                ('descripcion', models.CharField(max_length=50, verbose_name='')),
                ('cantidad', models.IntegerField(verbose_name='Número de productos a comprar')),
                ('preciototal', models.IntegerField(verbose_name='Precio de producto por cantidad')),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioPet.cliente')),
                ('codProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioPet.producto')),
            ],
        ),
    ]
