# Generated by Django 4.0.5 on 2022-06-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioPet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(verbose_name='Número de celular Cliente'),
        ),
    ]
