# Generated by Django 4.0.5 on 2022-06-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioPet', '0002_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripción de la compra de objeto(s)'),
        ),
    ]
