# Generated by Django 4.0.5 on 2022-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioPet', '0003_alter_boleta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fotoprod',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imágen de los productos'),
        ),
    ]
