# Generated by Django 4.0.5 on 2022-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioPet', '0004_producto_fotoprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='idBoleta',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de la boleta'),
        ),
    ]
