# Generated by Django 4.0.5 on 2022-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioPet', '0005_alter_boleta_idboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50, null=True, verbose_name='Correo Electrónico del Cliente'),
        ),
    ]
